name: ECS App Deploy

on:
  push:
    branches:
      - main
    paths:
      - "school-equipment/**"
      - ".github/workflows/deploy.yml"

  workflow_dispatch:
    inputs:
      image_tag:
        description: "Deploy image tag"
        required: false
        default: "latest"

env:
  AWS_REGION: eu-north-1
  APP_DIR: school-equipment
  ECR_REPOSITORY: school-equipment-system

jobs:
  build_and_push:
    name: Build & Push Image
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    outputs:
      image_url: ${{ steps.meta.outputs.image_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: ecr_login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set registry
        run: echo "ECR_REGISTRY=${{ steps.ecr_login.outputs.registry }}" >> $GITHUB_ENV

      - name: Build and Push Image
        id: meta
        env:
          IMAGE_TAG: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.image_tag || github.sha }}
        run: |
          IMAGE_URI="${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}"
          IMAGE_LATEST="${ECR_REGISTRY}/${ECR_REPOSITORY}:latest"

          docker build -f "${APP_DIR}/Dockerfile" -t "$IMAGE_URI" "$APP_DIR"
          docker tag "$IMAGE_URI" "$IMAGE_LATEST"

          docker push "$IMAGE_URI"
          docker push "$IMAGE_LATEST"

          echo "image_url=$IMAGE_URI" >> "$GITHUB_OUTPUT"

  terraform_update:
    name: Update ECS Service (New Image)
    runs-on: ubuntu-latest
    needs: build_and_push

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        working-directory: Infra
        run: terraform init

      - name: Terraform apply (update image only)
        working-directory: Infra
        run: |
          terraform apply -auto-approve \
            -var="image_url=${{ needs.build_and_push.outputs.image_url }}" \
            -var="domain_name=${{ secrets.DOMAIN_NAME }}" \
            -var="hosted_zone_name=${{ secrets.HOSTED_ZONE_NAME }}" \
            -var="hosted_zone_id=${{ secrets.HOSTED_ZONE_ID }}"