name: Docker Build and Push

on:
  push:
    branches:
      - main
    paths:
      - "app/ecs-assignment-main/**"
      - ".github/workflows/docker-build-push.yml"
  workflow_dispatch:

env:
  AWS_REGION: eu-north-1
  APP_DIR: app/ecs-assignment-main
  ECR_REPOSITORY: threatmod

jobs:
  build_and_push:
    name: Build and Push Image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: ecr_login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag and push image
        env:
          ECR_REGISTRY: ${{ steps.ecr_login.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          IMAGE_SHA_URI="${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}"
          IMAGE_LATEST_URI="${ECR_REGISTRY}/${ECR_REPOSITORY}:latest"

          docker build -f "${APP_DIR}/dockerfile" -t "${IMAGE_SHA_URI}" "${APP_DIR}"
          docker tag "${IMAGE_SHA_URI}" "${IMAGE_LATEST_URI}"

          docker push "${IMAGE_SHA_URI}"
          docker push "${IMAGE_LATEST_URI}"
