name: Terraform Infra Deploy

on:
  push:
    branches:
      - main
    paths:
      - "Infra/**"
      - ".github/workflows/terraform.yml"

  workflow_dispatch:

env:
  AWS_REGION: eu-north-1
  TF_DIR: Infra

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.9"

      - name: Terraform fmt
        working-directory: ${{ env.TF_DIR }}
        run: terraform fmt -check -recursive

      - name: Terraform init
        working-directory: ${{ env.TF_DIR }}
        run: terraform init

      - name: Terraform validate
        working-directory: ${{ env.TF_DIR }}
        run: terraform validate

      - name: Terraform plan
        working-directory: ${{ env.TF_DIR }}
        run: terraform plan -out=tfplan

      - name: Terraform apply
        working-directory: ${{ env.TF_DIR }}
        run: terraform apply -auto-approve tfplan